spring:
  application:
    name: config-client
  mvc:
    servlet:
      # path: /config-client 
      path: /
      
user:
  role: User-Narito



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
