spring:
  application:
    name: config-client

server:
  port: 0

user:
  role: Dev-Bob


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
