spring:
  application:
    name: config-client
  mvc:
    servlet:
      path: /housing-service #path for dispatcher servlet

server:
  port: 7777

user:
  role: Keye

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
