spring:
  application:
    name: config-client
  mvc:
    servlet:
      # path: /config-client
      path: /
      
  
server:
  port: 7456

user:
  role: Keye5

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
